id: aws_base
connection_type: aws
visible: true
connection_name: AWS
description: Configure a connection to AWS.
package: apache-airflow-providers-amazon
parameters:
  - airflow_param_name: aws_access_key_id
    friendly_name: Access Key ID
    description: AWS Access Key ID
    example: AKIAIOSFODNN7EXAMPLE
    type: str
    in_extra: true
    required: true
    secret: false
  - airflow_param_name: aws_secret_access_key
    friendly_name: Secret Access Key
    description: AWS Secret Access Key
    example: wJalrXUtnFEMI%2FK7MDENGbPxRfiCYEXAMPLEKEY
    type: str
    in_extra: true
    required: true
    secret: true
