id: weaviate_base
connection_type: weaviate
visible: false
connection_name: Weaviate
description: Weaviate is an opensource vector database with both hosted and containerized offerings for local development.
package: apache-airflow-providers-weaviate
parameters:
  # host
  - airflow_param_name: host
    friendly_name: Host
    type: str
    is_required: true
    is_secret: false
    description: The URL of the Weaviate cluster
    example: http://my-cluster.weaviate.network

  # additional_headers
  - airflow_param_name: additional_headers
    friendly_name: Connection Headers
    is_in_extra: true
    type: str
    is_required: false
    is_secret: true
    description: A json string for a dictionary of key/value pairs for additional connection headers.
    example: '{"additional_headers": {"X-OpenAI-Api-Key": "<OpenAI API KEY>"}}'
