id: github_base
connection_type: github
visible: true
connection_name: GitHub
description: Configure a GitHub connection
package: apache-airflow-providers-github
parameters:
  - airflow_param_name: password
    friendly_name: Access Token
    description: Personal access token with required permissions.
    example: ghp_abcdefghijk1234567890
    type: str
    is_required: true
    is_secret: true
    is_in_extra: false
  - airflow_param_name: host
    friendly_name: Host
    description: Specify the GitHub Enterprise URL when connecting to a GitHub Enterprise account.
    example: https://github.mydomain.com
    type: str
    is_required: false
    is_secret: false
    is_in_extra: false
