id: slack-webhook
connection_type: slackwebhook
visible: true
connection_name: Slack Webhook
description: The Slack Incoming Webhook connection type enables Slack Incoming Webhooks Integrations.
package: apache-airflow-providers-slack
parameters:
  - airflow_param_name: password
    friendly_name: Webhook Token
    description: Specify the Slack Incoming Webhook URL. If specified as a full url like https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX, the values from Slack Webhook Endpoint (Host) and Schema fields are ignored. If specified as a URL path like T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX, the Slack Incoming Webhook URL will build from this field, Schema and Slack Webhook Endpoint (Host).
    example: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
    type: str
    is_required: true
    is_secret: true
  - airflow_param_name: host
    friendly_name: Slack Webhook Endpoint (Host)
    description: Reference to slack webhook endpoint, if not specified than hooks.slack.com/services is used. If this value contains an http schema, then the schema parameter is ignored.
    example: hooks.slack.com/services
    type: str
    is_required: false
    is_secret: false
  - airflow_param_name: schema
    friendly_name: Schema
    description: Http schema, if not specified then https is used.
    example: https
    type: str
    is_required: false
    is_secret: false
  - airflow_param_name: timeout
    friendly_name: Timeout
    description: The maximum number of seconds the client will wait to connect and receive a response from Slack Incoming Webhook
    example: "60"
    type: int
    is_required: false
    is_secret: false
    is_in_extra: true
  - airflow_param_name: proxy
    friendly_name: Proxy
    description: Proxy to make the Slack Incoming Webhook call.
    example: "example.com"
    type: str
    is_required: false
    is_secret: false
    is_in_extra: true
