name: Validate prod

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "connections/prod/**"

jobs:
  restrict-job-to-devex-admins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Actor
        id: validate
        run: |
          if [[ ! "iancmoritz jlaneve melugoyal jeremybeard" =~ "$ACTOR" ]]; then
            echo "Error: $ACTOR is not allowed to run this action."
            exit 1
          fi
        env:
          ACTOR: ${{ github.actor }}

  validate-generated-json:
    needs: restrict-job-to-devex-admins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - run: pip install -r scripts/requirements.txt

      - name: Generate connection types from prod
        run: |
          python3 scripts/generate.py prod ${{ github.sha }}

      - name: Print connection types
        run: |
          cat prod-connection-types-request-body.json

      - name: Dry-Run prod connections
        run: |
          RESPONSE_BODY=$(curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.PROD_BEARER_TOKEN }}" -d @prod-connection-types-request-body.json https://api.astronomer.io/registryV2/v1alpha1/organizations/org-astro-dev-ex/connection-types?isDryRun=true)
          EXPECTED_BODY='{"message":"All connections are valid"}'

          if [[ "$RESPONSE_BODY" != "$EXPECTED_BODY" ]]; then
            echo "Received error: $RESPONSE_BODY"
            exit 1
          fi
